backend:
  name: git-gateway
  branch: main

locale: de

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: "/assets/uploads"
    public_folder: "/assets/uploads"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: false }
      - { label: "Kategorie", name: "category", widget: "select", options: ["Vereinsanlass", "Wettbewerb", "Wichtig", "Sonstiges"] }
      - { label: "Teaser", name: "teaser", widget: "text" }
      - { label: "Text", name: "body", widget: "markdown", required: false }
      - { label: "Bild", name: "image", widget: "image", required: false }
      - { label: "Link URL", name: "url", widget: "string", required: false }
      - { label: "Ver√∂ffentlicht", name: "published", widget: "boolean", default: true }
